version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    command: gunicorn cookie_stand.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - "8000:8000"
#    depends_on:
#        - db
#  db:
#    image: postgres
#    environment:
#        - POSTGRES_DB=${POSTGRES_DB}
#        - POSTGRES_USER=${POSTGRES_USER}
#        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    volumes:
#        - postgres_data:/var/lib/postgresql/data/
#
#volumes:
#    postgres_data: